CREATE TABLE `rifa` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`num` INT(10) UNSIGNED NULL DEFAULT NULL,
	`nome` VARCHAR(100) NULL DEFAULT NULL,
	`telefone` VARCHAR(15) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
